# Generated by Django 4.1.4 on 2022-12-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='commented_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follower_id',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='following_id',
            new_name='following',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='liked_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='created_by',
            new_name='user',
        ),
    ]
